title: There's No Moon Over the Web
email: nomoon@phoebus.ca
description: Sanskrit Digital Humanities & Software Development
baseurl: ""
url: "https://nomoon.github.io/"
twitter_username: nomoon
github_username:  nomoon
lang: en_CA

# Build settings
markdown: kramdown
theme: jekyll-whiteglass
exclude:
  - Gemfile
  - Gemfile.lock
  - .ruby-gemset
  - .ruby-version
  - .autoenv.zsh
  - .autoenv_leave.zsh
  - bin/
